"""empty message

Revision ID: 47fdd2fe57f4
Revises: f3919a6391b1
Create Date: 2023-11-19 01:47:04.675102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fdd2fe57f4'
down_revision = 'f3919a6391b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticky_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sticky_note', schema=None) as batch_op:
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###
